Add filter for description containing text
DSSD-Madison/Red-CORAL pull request #88
Opened 2024-12-03 23:53 UTC by LostBitset

See #69

2024-12-03 23:59 UTC, LostBitset commented
Should be ready @TetraTsunami

2024-12-04 22:51 UTC, TetraTsunami requested changes
See the comments. The core functionality is perfect but perhaps overly complex for what it needs to accomplish.

2024-12-04 22:51 UTC, TetraTsunami commented on pnpm-lock.yaml
I wish we used pnpm too, but this project is currently set up with npm and I'd rather not change it this late in the semester. You should delete this file.

2024-12-04 22:51 UTC, TetraTsunami commented on src/components/filters/DescFilter.tsx
I'm so sorry you had to do this. It's my fault for mentioning the date filter in your issue, since it got updated in a PR to have many more features. This is the version I was referring to: https://github.com/DSSD-Madison/Red-CORAL/blob/6e90d04d5b995e8062501357a55a2ad70a62c9f5/src/components/filters/DateFilter.tsx

Most notably, you don't need the dropdown-within-a-dropdown with multiple options since there will only ever be one (contains). This should let you remove a lot of code and simplify it tremendously.

Other than that, this works well!

2024-12-04 22:51 UTC, TetraTsunami commented on src/components/filters/DescFilter.tsx
> +          Fecha {selectedDescFilter}
This isn't the date filter anymore, so you should remove references to that.

```suggestion
          La descripción {selectedDescFilter}
```

2024-12-04 22:51 UTC, TetraTsunami commented on src/components/filters/DescFilter.tsx
> +        dispatch({ type: 'UPDATE_FILTER', payload: { id: id, operation: (incident) => incident.description.includes(search) } })
I wonder if you could make this case-insensitive? It doesn't seem likely that users will want to filter only by capitalization.

2024-12-12 16:13 UTC, the-snesler approved these changes

2024-12-12 16:13 UTC, merged